"""rename department

Revision ID: 386f30600369
Revises: 84e1213443a1
Create Date: 2026-01-04 09:28:44.238421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386f30600369'
down_revision = '84e1213443a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
