"""Initial migration

Revision ID: 529bd02beb17
Revises: 
Create Date: 2026-01-04 09:07:22.417952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529bd02beb17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
