"""Add address column to Department

Revision ID: 78a7ce71f770
Revises: 0c1b9655fe21
Create Date: 2026-01-04 09:23:00.170224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a7ce71f770'
down_revision = '0c1b9655fe21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
