"""rename department

Revision ID: 84e1213443a1
Revises: 78a7ce71f770
Create Date: 2026-01-04 09:25:59.517317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e1213443a1'
down_revision = '78a7ce71f770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
