"""rename address

Revision ID: e45f0bcbbc5b
Revises: 386f30600369
Create Date: 2026-01-04 09:35:17.828995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45f0bcbbc5b'
down_revision = '386f30600369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
